### ISSUE TITLE
地図つくるよ

### ISSUE THREAD

**Issue by shu000** [ebc0729/RailApp#11]
よくわからないよ

**Comment by hiracky16** [comment]
https://github.com/hiracky16/RailRoad
これ参考にしてみてください
これはOpen Street Map というフリーの地図を使った leaflet.js というライブラリを使って地図描画しています。
このライブラリの地図がダサいので mapbox の地図で置き換えたいです。
なので調査からやってほしいです…
参考: [mapbox](https://www.mapbox.com/)

**Comment by shu000** [comment]
アイジーアールいわて銀河鉄道マッピングてすと
http://52.199.230.181/mymaps/

**Comment by hiracky16** [comment]
`feature/test-map_box` ブランチで全線路データを地図の上に表示しています。
mapbox のアクセストークンを環境変数にするやり方はまた別でまとめます。

**Comment by hiracky16** [comment]
mapbox の token値 を外出する方法を書きました。
http://h-piiice16.hatenablog.com/entry/2017/12/10/160711

JSで使う変数だけでなく Rails の方でも公開したくない変数などあったら それぞれの .env に書くのが一般的らしいです。

**Comment by hiracky16** [comment]
地図はマージされたのでクローズします。
