### ISSUE TITLE
残りすべてのviewとリンクの作成

### ISSUE THREAD

**Issue by morinokumakamesan** [ebc0729/RailApp#18]
足りないviewとそれぞれのviewで足りないリンクを生成する．

足りないview
- [x] 登録内容確認画面
- [x] 登録しました画面

足りないリンク
- [x] 「地図を見る」→「ログアウト」，「会員情報変更」，「help」，「記録する」
- [x] 「記録を見る」→「ログアウト」，「会員情報変更」，「help」
- [x] 「記録する」→「ログアウト」，「会員情報変更」，「help」，「地図を見る」，「登録内容確認画面」
- [x] 「登録内容確認画面」→「ログアウト」，「会員情報変更」，「help」，「登録しました画面」
- [x] 「登録しました画面」→「ログアウト」，「会員情報変更」，「help」，「記録する」

足りていないのを発見したので追加します
- [x] 「会員情報変更」→「ログアウト」，「会員情報変更」，「help」
- [x] 「help」→「ログアウト」，「会員情報変更」，「help」

**Comment by hiracky16** [comment]
一旦できたんでクローズ
