### ISSUE TITLE
足りないviewを発見したので作ります

### ISSUE THREAD

**Issue by morinokumakamesan** [ebc0729/RailApp#19]
- [x] 退会画面
- [x] 「退会画面」→「ログアウト」，「会員情報変更」，「help」
- [ ] 変更が完了しました画面
- [ ] 「変更が完了しました画面」→「ログアウト」，「会員情報変更」，「help」，「トップへ」

**Comment by hiracky16** [comment]
会員情報変更画面の中のフォームとかも一緒に作ってください
- [ ] 会員変更フォーム

**Comment by hiracky16** [comment]
会員情報変更完了画面はいらないと思うので、このイシューはクローズします。
