### ISSUE TITLE
ログインページの組み込み

### ISSUE THREAD

**Issue by hiracky16** [ebc0729/RailApp#28]
デザインファイル
https://github.com/ebc0729/RailApp/tree/develop/create-design-file/public/design-file
これの実装

**Comment by hiracky16** [comment]
@shu000 
これ対応お願いできないでしょうか？

**Comment by shu000** [comment]
@hiracky16
はーい

**Comment by shu000** [comment]
fix @2210dbdf71a2df5cfd3e150665b134583401a062 to @0912d1a172f22e3d69e36259f0822ee51551e423

**Comment by shu000** [comment]
ひとまずサインインページのデザイン反映しました。
（次回以降コミットコメントに issueID 付けます。。。）

**Comment by hiracky16** [comment]
@shu000 
コミットにID付与するの良いですね！
プルリクエスト作るの忘れてません？

**Comment by shu000** [comment]
@hiracky16 
#32 でおけかな？
不慣れなものでどうも。。。

**Comment by hiracky16** [comment]
@shu000 
Asignee にアサインしたい人を選んで、その人達に「確認お願いします」的なコメント残してもらうと完璧です

**Comment by hiracky16** [comment]
組み込み済み
クローズ
