### ISSUE TITLE
会員情報の変更

### ISSUE THREAD

**Issue by morinokumakamesan** [ebc0729/RailApp#35]
ニックネームを実装しています。
ブランチ名はfeature/edit_usertableでマイグレーションしました。

- [x] マイグレーション
- [x] 登録フォーム
- [x] ログインフォーム
- [x] 編集フォーム

**Comment by hiracky16** [comment]
伝え忘れかもしれないけど、下記のカラムも追加予定です。
- [ ] 年代
- [ ] 性別
- [ ] 好きな路線
https://drive.google.com/file/d/17eyp9JCjBs1Fq4GVwyGT2so9wgBdGK3F/view?usp=sharing
このWFに乗ってる項目です。

**Comment by hiracky16** [comment]
@morinokumakamesan 引き取ります

**Comment by hiracky16** [comment]
User テーブルには nickname に当たる username というカラムがすでに存在するの追加しません。

**Comment by hiracky16** [comment]
クローズします
